### ISSUE TITLE
Implement Fleet Model

### ISSUE THREAD

**Issue by NamBlue** [COMP4711AS01-BLUEBIRD/COMP4711AS01#10]
Fleet - the planes that make up your airline's fleet.
You will need a unique identifier for each airplane, and the kind of plane it is. Any other information is up to you.

Your fleet can consist of any number and kind of recognized airplanes, subject to a budget limit of $10M. Your app will not be load-tested as part of assignment 1, and you can change your fleet for later assignments.

**Comment by kdw313** [comment]
fleet finished
data template is following

 'id'            =>
 'manufacturer'  =>
 'model'         =>
 'seats'         =>
 'reach'         =>
 'cruise'        =>
 'takeoff'       =>
 'hourly'        =>
